"""Primary evidence sources used by the grading website and report engine."""

RESEARCH_SOURCES = [
    {
        "type": "dataset_paper",
        "title": "An annotated human blastocyst dataset to benchmark deep learning architectures for in vitro fertilization",
        "year": 2022,
        "doi": "10.1038/s41597-022-01848-y",
        "url": "https://doi.org/10.1038/s41597-022-01848-y",
        "usage": "Open benchmark dataset design and image-label schema for AI model development.",
    },
    {
        "type": "dataset",
        "title": "Annotated Human Blastocyst Dataset (Figshare)",
        "year": 2022,
        "doi": "10.6084/m9.figshare.20123153.v3",
        "url": "https://doi.org/10.6084/m9.figshare.20123153.v3",
        "usage": "Public image/label source for custom training pipelines.",
    },
    {
        "type": "consensus",
        "title": "Istanbul consensus workshop on embryo assessment",
        "year": 2011,
        "doi": "10.1093/humrep/der037",
        "url": "https://doi.org/10.1093/humrep/der037",
        "usage": "Standardized morphology terminology and baseline grading framework.",
    },
    {
        "type": "consensus_update",
        "title": "Update to the Istanbul consensus recommendations",
        "year": 2025,
        "doi": "10.1093/hropen/hoaf023",
        "url": "https://doi.org/10.1093/hropen/hoaf023",
        "usage": "Updated framework and reporting guidance for embryo morphology grading.",
    },
    {
        "type": "grading_outcomes",
        "title": "Multinational multicentre analysis of blastocyst morphology and live birth after single transfer",
        "year": 2023,
        "doi": "10.1093/humrep/dead301",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10694400/",
        "usage": "Large mixed cohort rates by morphology groups and AC/BC/CB/CC subclasses.",
    },
    {
        "type": "grading_outcomes",
        "title": "Association between embryo morphology and successful euploid blastocyst transfer outcome in natural cycle frozen embryo transfer",
        "year": 2022,
        "doi": "10.1007/s10815-022-02468-8",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8995226/",
        "usage": "Euploid cohort outcomes by full ICM/TE pair (AA, AB, BA, BB, AC/CA/BC/CB/CC).",
    },
    {
        "type": "grading_outcomes",
        "title": "Effect of trophectoderm and inner cell mass quality on pregnancy outcomes in single blastocyst transfer cycles and related perinatal outcomes",
        "year": 2021,
        "doi": "10.1186/s12958-021-00846-8",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8589796/",
        "usage": "Additional large FET cohort with stage/ICM/TE-specific live birth and adjusted risks.",
    },
    {
        "type": "meta_analysis",
        "title": "Association between blastocyst morphology and treatment outcomes in frozen embryo transfer cycles: a network meta-analysis",
        "year": 2025,
        "doi": "10.3390/jcm14113563",
        "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12194673/",
        "usage": "Cross-study morphology ranking trend (AA, AB, BA, BB generally highest-performing).",
    },
    {
        "type": "historical",
        "title": "Blastocyst score affects implantation and pregnancy outcome",
        "year": 2000,
        "doi": "10.1016/S0015-0282(00)01418-5",
        "url": "https://doi.org/10.1016/S0015-0282(00)01418-5",
        "usage": "Original clinical association report for morphology and outcomes.",
    },
]
